name: obs_collections_generator
description: A sample command-line application.
version: 1.2.3

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  args: ^2.3.0
  yaml: ^3.1.0
  archive: ^3.1.11

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
