name: collections_archive_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  yaml: ^3.1.0
  archive: ^3.1.11

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
