name: add artifact links to pull request and related issues
on:
  workflow_run:
    workflows: [Main workflow]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: add artifact links to pull request and related issues job
    runs-on: ubuntu-latest
    steps:
      - name: add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pullState: all
          prefix: Here is the generated executable by OS.
          format: name
          addTo: pull