name: Add artifacts links to pull request and related issues.
on:
  workflow_run:
    workflows:
      - "Main workflow"
    types:
      - completed


jobs:
  artifacts-url-comments:
    name:  Add artifacts links to pull request and related issues.
    runs-on: ubuntu-latest
    steps:
      - uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pullState: all
          prefix: Here is the generated executable by OS.
          format: name
          addTo: pull
