name: Main workflow
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
jobs:
  tag_validation:
    name: Tag validation
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.split.outputs._0 }}
    steps:
      - uses: actions/checkout@v2
      - name: Get the version from the pubspec
        id: pubspec_version
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: pubspec.yaml
          version: version
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ steps.pubspec_version.outputs.version }}
          seperator: '+'
      - name: Validate that version doesn't exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: check_tag
        with:
          tag: ${{ steps.split.outputs._0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.check_tag.outputs.exists == 'true' && github.event_name == 'pull_request' }}
        name: Post comment on PR
        uses: thollander/actions-comment-pull-request@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: '${{ steps.split.outputs._0 }} already exists, please update the pubspec version.'
      - if: ${{ steps.check_tag.outputs.exists == 'true' }}
        name: Fails because the tag already exists.
        run: exit 1
  testing:
    name: Tests, analyse and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3
      - name: Get dependencies
        run: dart pub get
      - name: Format files in lib, test and bin directories
        run: dart format lib test bin
      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*.dart"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "BOT Applying dart format."
          add_options: '-u'
      - name: Analyse code
        run: dart analyze
      - name: Execute tests
        run: dart test --coverage=coverage
      - name: Upload coverage file
        uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: ./coverage/lcov.info
  coverage:
    name: Update coverage
    needs: [ testing ]
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage file
        uses: actions/download-artifact@v2
        with:
          name: lcov.info
      # Comment coverage report
      - name: Comment the coverage of the PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./lcov.info
#       Disabled for now.
#      - name: Update badge coverage
#        if: ${{ github.event_name == 'push' }}
#        uses: schneegans/dynamic-badges-action@v1.1.0
#        with:
#          auth: ${{ secrets.GIST_COVERAGE_BADGE_TOKEN }}
#          gistID: ${{ secrets.GIST_ID_COVERAGE_BADGE }}
#          filename: notre_dame_master_badge_coverage.json
#          label: Code coverage
#          message: ${{ needs.testing.outputs.coverage }}
#          namedLogo: flutter
#          color: green
  build:
    name: Build the CLI for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target: [ linux, macos, windows ]
        include:
          - target: linux
            os: ubuntu-latest
            output: obs_collections_generator_linux
          - target: macos
            os: macos-latest
            output: obs_collections_generator_macos
          - target: windows
            os: windows-latest
            output: obs_collections_generator_windows.exe
    needs:
      - testing
      - tag_validation
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.3
      - name: Get dependencies
        run: dart pub get
      - name: Building executable
        run: dart compile exe bin/obs_collections_generator.dart -o ${{ matrix.output }}
      - name: Upload ${{ matrix.target }} build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}_build
          path: ${{ github.workspace }}/${{ matrix.output }}
  create_release:
    name: Github pre-release
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs:
      - tag_validation
      - build
    steps:
      - name: Download Windows build
        uses: actions/download-artifact@v2
        with:
          name: windows_build
      - name: Download Linux build
        uses: actions/download-artifact@v2
        with:
          name: linux_build
      - name: Download MacOS build
        uses: actions/download-artifact@v2
        with:
          name: macos_build
      - name: Create pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ needs.tag_validation.outputs.version }}
          prerelease: true
          title: v${{ needs.tag_validation.outputs.version }}
          files: |
            obs_collections_generator_linux
            obs_collections_generator_macos
            obs_collections_generator_windows.exe